version: '3'
services:
  loomi-api:
    container_name: loomi-api
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - loomi-db
    depends_on:
      - loomi-db
    environment:
      WAIT_HOSTS: loomi-db:27017
      DB_HOST: loomi-db:27017
      DB_NAME: loomi-db
  loomi-db:
    container_name: loomi-db
    hostname: loomi-db
    restart: always
    image: mongo
    volumes:
      - /Users/$USER/data/loomi-db:/data/db
    ports:
      - '27017:27017'
