version: '3'
services:
  loomi-api:
    container_name: loomi-api
    restart: unless-stopped
    build: .
    ports:
      - '80:3000'
    links:
      - loomi-db
    depends_on:
      - loomi-db
    environment:
      WAIT_HOSTS: loomi-db:27017
      DB_HOST: loomi-db:27017
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PWD: $DB_PWD
  loomi-db:
    container_name: loomi-db
    hostname: loomi-db
    restart: unless-stopped
    image: mongo
    volumes:
      - $HOME/data/loomi-db:/data/db
      - $PWD/mongo:/docker-entrypoint-initdb.d
      - $PWD/.env:/.env
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_ROOT_PWD
